/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetCapabilitiesResponse {
  title: string;
  layers: Layers[];
}
export interface Layers {
  name: string;
  title: string;
  abstract?: string;
  groupName?: string;
  groupTitle?: string;
  keywordList?: KeywordList[];
  externalForecastTime?: string;
  ensembles?: Ensemble[];
  timesDefault?: string;
  times?: string[];
  /**
   * Set to true if this layer has only missing values. Null in case it is unknown (from archive).
   */
  completelyMissing?: boolean | null;
  /**
   * First time step from the time array that has a value. Null in case it is unknown (from archive).
   */
  firstValueTime?: string | null;
  /**
   * Last time step from the times array that has a value. Null in case it is unknown (from archive).
   */
  lastValueTime?: string | null;
  elevation?: {
    units?: string;
    lowerValue?: string;
    upperValue?: string;
  };
  styles?: Style[];
}
export interface KeywordList {
  parameterId?: string;
  locationId?: string;
  moduleInstanceId?: string;
  timeSeriesType?: "EXTERNAL_HISTORICAL" | "EXTERNAL_FORECASTING" | "SIMULATED_HISTORICAL" | "SIMULATED_FORECASTING";
  ensembleId?: string;
  ensembleMemberId?: string;
  forecastTime?: string;
}
export interface Ensemble {
  ensembleId: string;
  ensembleMemberIds: string[];
}
export interface Style {
  name?: string;
  title: string;
}
